#
# Conda environment definition with dependencies
#
name: runs_n_poses
channels:
  - metalcycling
  - conda-forge
  - aivant
  - defaults
  - bioconda
dependencies:
  - python=3.10.*
  - reduce
  - aivant::openstructure=2.8.0
  - boost=1.82
  - rdkit
  - pandas
  - ipykernel
  - jupyter
  - pip:
    - plinder
    - scikit-learn
    - cmap
    - keyrings.google-artifactregistry-auth==1.1.2